const base=[
{name:"Сахар",cat:"Сахар и сироп",kg:94.58,solids:99.85,key:"sugar"},
{name:"Кислота лимонная, моногидрат",cat:"Кислота",kg:1.55,solids:90.97,key:"acid"},
{name:"Ароматизатор Дюшес AN1374",cat:"Ароматизатор",kg:.29,solids:null},
{name:"КПД «Ароматик», раствор красителей «Дюшес»",cat:"Краситель",kg:.10,solids:null},
{name:"КПД «Ароматик», раствор красителя «Шоколад»",cat:"Краситель",kg:.12,solids:null},
{name:"Бензоат натрия",cat:"Консервант",kg:.17,solids:99.90,key:"benzoate"},
{name:"Диоксид углерода",cat:"Диоксид углерода",kg:4.15,solids:0}
];let items=JSON.parse(localStorage.getItem("bs_items")||"null")||structuredClone(base);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=(n,d=2)=>Number(n).toLocaleString("ru-RU",{minimumFractionDigits:d,maximumFractionDigits:d});
function scale(){return (+$("#volume").value||1000)/1000*(1+(+$("#loss").value||0)/100)}
function render(){let sc=scale(),tb=$("#ingredients");tb.innerHTML="";items.forEach((x,i)=>{let sv=x.solids==null?null:x.kg*sc*x.solids/100;let tr=document.createElement("tr");tr.innerHTML=`<td><div class=name>${x.name}</div></td><td><span class=category>${x.cat}</span></td><td><input type=number step=.001 value="${(x.kg*sc).toFixed(3)}" data-i=${i} data-f=kg></td><td><input type=number step=.01 placeholder="Не задано" value="${x.solids??""}" data-i=${i} data-f=solids></td><td>${sv==null?"—":fmt(sv,3)}</td><td><button class=remove data-r=${i}>×</button></td>`;tb.appendChild(tr)});
tb.querySelectorAll("input").forEach(el=>el.onchange=e=>{let i=+e.target.dataset.i,f=e.target.dataset.f;if(f==="kg")items[i].kg=(+e.target.value||0)/scale();else items[i].solids=e.target.value===""?null:+e.target.value;persist();render()});
tb.querySelectorAll("[data-r]").forEach(b=>b.onclick=()=>{items.splice(+b.dataset.r,1);persist();render()});calc();doc();renderA4()}
function calc(){let sc=scale(),vol=+$("#volume").value||1000,ratio=+$("#ratio").value||4,syr=vol/(1+ratio);$("#syrupVolume").textContent=fmt(syr)+" л";let known=items.reduce((a,x)=>a+(x.solids==null?0:x.kg*sc*x.solids/100),0);let sugar=items.find(x=>x.key==="sugar"),acid=items.find(x=>x.key==="acid"),benz=items.find(x=>x.key==="benzoate");let sugarSV=sugar&&sugar.solids!=null?sugar.kg*sc*sugar.solids/100:0;let inv=known+sugarSV*.0526;$("#fresh").textContent=fmt(known/vol*100);$("#inverted").textContent=fmt(inv/vol*100);$("#syrupBrix").textContent=fmt(known/syr*100);$("#acidity").textContent=acid?fmt((acid.kg*sc*1000/vol)/.7005):"—";let benzoic=benz?benz.kg*sc*1e6/vol*(122.12/144.11):0;$("#benzoic").textContent=fmt(benzoic,1)}
function doc(){let sc=scale(),vol=+$("#volume").value||1000,ratio=+$("#ratio").value||4,syr=vol/(1+ratio);$("#docSubtitle").textContent=`Рецептура на ${fmt(syr,2)} дм³ сиропа или на ${fmt(vol,0)} дм³ готового напитка (без учёта потерь).`;const tnpa={"Сахар":"ГОСТ 33222-2015","Кислота лимонная, моногидрат":"ГОСТ 908","Ароматизатор Дюшес AN1374":"ТУ BY 100534628.026","КПД «Ароматик», раствор красителей «Дюшес»":"ТУ BY 100534628.022","КПД «Ароматик», раствор красителя «Шоколад»":"ТУ BY 100534628.022","Бензоат натрия":"По документам, подтверждающим качество и безопасность"};let rows=items.filter(x=>x.name!=="Диоксид углерода").map(x=>`<tr><td>${x.name}</td><td>${tnpa[x.name]||""}</td><td>кг</td><td>${fmt(x.kg*sc,2)}</td><td>${x.solids==null?"":fmt(x.solids,2)}</td><td>${x.solids==null?"":fmt(x.kg*sc*x.solids/100,2)}</td></tr>`).join("");rows+=`<tr><td>Вода</td><td>СТБ 1188, СанПиН 10-124</td><td>дм³</td><td>до ${fmt(syr,2)}</td><td></td><td></td></tr><tr class="section-row"><td colspan="6">Для приготовления напитка</td></tr><tr><td>Вода</td><td>СТБ 1188, СанПиН 10-124</td><td>дм³</td><td>до ${fmt(vol,0)}</td><td></td><td></td></tr>`;let co2=items.find(x=>x.name==="Диоксид углерода");if(co2)rows+=`<tr><td>Двуокись углерода</td><td>ГОСТ 8050</td><td>кг</td><td>${fmt(co2.kg*sc,2)}</td><td></td><td></td></tr>`;$("#docTable").innerHTML=`<table class="print-main"><thead><tr><th rowspan="2">Наименование сырья</th><th rowspan="2">ТНПА на сырьё</th><th colspan="2">Содержание сырья в готовом сиропе</th><th colspan="2">Содержание сухих веществ в сырье</th></tr><tr><th>Ед. изм.</th><th>Количество</th><th>Массовая доля, %</th><th>Масса, кг</th></tr></thead><tbody><tr class="section-row"><td colspan="6">Для приготовления сиропа</td></tr>${rows}</tbody></table>`;let known=items.reduce((s,x)=>s+(x.solids==null?0:x.kg*sc*x.solids/100),0),sugar=items.find(x=>x.key==="sugar"),sugarSV=sugar&&sugar.solids!=null?sugar.kg*sc*sugar.solids/100:0,growth=sugarSV*.0526;$("#printTotals").innerHTML=`<table class="print-main totals"><tbody><tr><td>Итого сухих веществ</td><td>${fmt(known,2)} кг</td></tr><tr><td>Прирост сухих веществ за счёт 100%-ной инверсии сахарозы</td><td>${fmt(growth,2)} кг</td></tr><tr><td><b>Всего сухих веществ в полностью инвертированном напитке</b></td><td><b>${fmt(known+growth,2)} кг</b></td></tr></tbody></table>`;} 
function renderA4(){
 let sc=scale(),vol=+$("#volume").value||1000,ratio=+$("#ratio").value||4,syr=vol/(1+ratio);
 $("#a4Subtitle").textContent=`Рецептура на ${fmt(syr,2)} дм³ сиропа или на ${fmt(vol,0)} дм³ готового напитка (без учета потерь).`;
 const tnpa={"Сахар":"ГОСТ 33222-2015","Кислота лимонная, моногидрат":"ГОСТ 908","Ароматизатор Дюшес AN1374":"ТУ BY 100534628.026","КПД «Ароматик», раствор красителей «Дюшес»":"ТУ BY 100534628.022","КПД «Ароматик», раствор красителя «Шоколад»":"ТУ BY 100534628.022","Бензоат натрия":"По документам, подтверждающим качество и безопасность"};
 let html='<tr class="section"><td colspan="6">Для приготовления сиропа</td></tr>';
 items.filter(x=>x.name!=="Диоксид углерода").forEach(x=>{let mass=x.solids==null?'':fmt(x.kg*sc*x.solids/100,2);html+=`<tr><td>${x.name}</td><td>${tnpa[x.name]||''}</td><td>кг</td><td>${fmt(x.kg*sc,2)}</td><td>${x.solids==null?'':fmt(x.solids,2)}</td><td>${mass}</td></tr>`});
 html+=`<tr><td>Вода</td><td>СТБ 1188, СанПиН 10-124</td><td>дм³</td><td>до ${fmt(syr,2)}</td><td></td><td></td></tr><tr><td>Выход сиропа</td><td></td><td>дм³</td><td>${fmt(syr,2)}</td><td></td><td></td></tr><tr class="section"><td colspan="6">Для приготовления напитка</td></tr><tr><td>Вода</td><td>СТБ 1188, СанПиН 10-124</td><td>дм³</td><td>до ${fmt(vol,0)}</td><td></td><td></td></tr>`;
 let co2=items.find(x=>x.name==="Диоксид углерода");if(co2)html+=`<tr><td>Двуокись углерода</td><td>ГОСТ 8050</td><td>кг</td><td>${fmt(co2.kg*sc,2)}</td><td></td><td></td></tr>`;
 let known=items.reduce((a,x)=>a+(x.solids==null?0:x.kg*sc*x.solids/100),0),sugar=items.find(x=>x.key==="sugar"),sugarSV=sugar&&sugar.solids!=null?sugar.kg*sc*sugar.solids/100:0,growth=sugarSV*.0526;
 html+=`<tr><td>Итого сухих веществ</td><td></td><td>кг</td><td></td><td></td><td>${fmt(known,2)}</td></tr><tr><td>Прирост сухих веществ за счёт<br>100-% инверсии сахарозы</td><td></td><td>кг</td><td></td><td></td><td>${fmt(growth,2)}</td></tr><tr><td>Всего сухих веществ в полностью<br>инвертированном напитке</td><td></td><td>кг</td><td></td><td></td><td>${fmt(known+growth,2)}</td></tr>`;
 $("#a4Rows").innerHTML=html;
}
function persist(){localStorage.setItem("bs_items",JSON.stringify(items))}
["volume","ratio","loss"].forEach(id=>$("#"+id).oninput=render);
$("#reset").onclick=()=>{items=structuredClone(base);localStorage.removeItem("bs_items");$("#volume").value=1000;$("#ratio").value=4;$("#loss").value=0;render()};
$("#save").onclick=()=>{persist();localStorage.setItem("bs_lab",JSON.stringify({fresh:$("#labFresh").value,inv:$("#labInv").value,acid:$("#labAcid").value,note:$("#labNote").value}));alert("Версия сохранена на этом устройстве.")};
$("#add").onclick=()=>{let name=prompt("Название сырья:");if(name){items.push({name,cat:"Другое",kg:0,solids:null});persist();render()}};
$$(".tab").forEach(b=>b.onclick=()=>{$$(".tab").forEach(x=>x.classList.remove("active"));$$(".tabpane").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.tab).classList.add("active")});
$$(".nav").forEach(b=>b.onclick=()=>{$$(".nav").forEach(x=>x.classList.remove("active"));$$(".view").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.view).classList.add("active")});
$("#theme").onclick=()=>document.body.classList.toggle("dark");
let lab=JSON.parse(localStorage.getItem("bs_lab")||"{}");$("#labFresh").value=lab.fresh||"";$("#labInv").value=lab.inv||"";$("#labAcid").value=lab.acid||"";$("#labNote").value=lab.note||"";
$("#csv").onclick=()=>{let rows=[["Наименование","Количество, кг","СВ, %"],...items.map(x=>[x.name,(x.kg*scale()).toFixed(3),x.solids??""])];let csv="\ufeff"+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(";")).join("\n");let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download="beverage_studio_recipe.csv";a.click()};
render();