const base=[
{name:"Сахар",cat:"Сахар и сироп",kg:94.58,solids:99.85,key:"sugar"},
{name:"Кислота лимонная, моногидрат",cat:"Кислота",kg:1.55,solids:90.97,key:"acid"},
{name:"Ароматизатор Дюшес AN1374",cat:"Ароматизатор",kg:.29,solids:null},
{name:"КПД «Ароматик», раствор красителей «Дюшес»",cat:"Краситель",kg:.10,solids:null},
{name:"КПД «Ароматик», раствор красителя «Шоколад»",cat:"Краситель",kg:.12,solids:null},
{name:"Бензоат натрия",cat:"Консервант",kg:.17,solids:99.90,key:"benzoate"},
{name:"Диоксид углерода",cat:"Диоксид углерода",kg:4.15,solids:0}
];
let items=JSON.parse(localStorage.getItem("bs_items")||"null")||structuredClone(base);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=(n,d=2)=>Number(n).toLocaleString("ru-RU",{minimumFractionDigits:d,maximumFractionDigits:d});
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function scale(){return (+$("#volume").value||1000)/1000*(1+(+$("#loss").value||0)/100)}
function tnpaFor(name){return ({"Сахар":"ГОСТ 33222-2015","Кислота лимонная, моногидрат":"ГОСТ 908","Кислота лимонная":"ГОСТ 908","Ароматизатор Дюшес AN1374":"ТУ BY 100534628.026","КПД «Ароматик», раствор красителей «Дюшес»":"ТУ BY 100534628.022","КПД «Ароматик», раствор красителя «Шоколад»":"ТУ BY 100534628.022","Бензоат натрия":"По документам, подтверждающим качество и безопасность"})[name]||""}
function render(){let sc=scale(),tb=$("#ingredients");tb.innerHTML="";items.forEach((x,i)=>{let sv=x.solids==null?null:x.kg*sc*x.solids/100;let tr=document.createElement("tr");tr.innerHTML=`<td data-label="Сырьё"><div class="name">${esc(x.name)}</div><div class="mobile-category">${esc(x.cat)}</div></td><td data-label="Категория"><span class="category">${esc(x.cat)}</span></td><td data-label="Количество, кг"><input type="number" step=".001" value="${(x.kg*sc).toFixed(3)}" data-i="${i}" data-f="kg"></td><td data-label="СВ сырья, %"><input type="number" step=".01" placeholder="Не задано" value="${x.solids??""}" data-i="${i}" data-f="solids"></td><td data-label="СВ, кг">${sv==null?"—":fmt(sv,3)}</td><td class="remove-cell"><button class="remove" data-r="${i}" aria-label="Удалить">×</button></td>`;tb.appendChild(tr)});
tb.querySelectorAll("input").forEach(el=>el.onchange=e=>{let i=+e.target.dataset.i,f=e.target.dataset.f;if(f==="kg")items[i].kg=(+e.target.value||0)/scale();else items[i].solids=e.target.value===""?null:+e.target.value;persist();render()});
tb.querySelectorAll("[data-r]").forEach(b=>b.onclick=()=>{items.splice(+b.dataset.r,1);persist();render()});calc();renderDocumentPreview()}
function calc(){let sc=scale(),vol=+$("#volume").value||1000,ratio=+$("#ratio").value||4,syr=vol/(1+ratio);$("#syrupVolume").textContent=fmt(syr)+" л";let known=items.reduce((a,x)=>a+(x.solids==null?0:x.kg*sc*x.solids/100),0);let sugar=items.find(x=>x.key==="sugar"),acid=items.find(x=>x.key==="acid"),benz=items.find(x=>x.key==="benzoate");let sugarSV=sugar&&sugar.solids!=null?sugar.kg*sc*sugar.solids/100:0;let inv=known+sugarSV*.0526;$("#fresh").textContent=fmt(known/vol*100);$("#inverted").textContent=fmt(inv/vol*100);$("#syrupBrix").textContent=fmt(known/syr*100);$("#acidity").textContent=acid?fmt((acid.kg*sc*1000/vol)/.7005):"—";let benzoic=benz?benz.kg*sc*1e6/vol*(122.12/144.11):0;$("#benzoic").textContent=fmt(benzoic,1)}
function documentBody(){
 let sc=scale(),vol=+$("#volume").value||1000,ratio=+$("#ratio").value||4,syr=vol/(1+ratio);
 let rows='<tr class="band"><td colspan="6">Для приготовления сиропа</td></tr>';
 items.filter(x=>x.name!=="Диоксид углерода").forEach(x=>{let mass=x.solids==null?'':fmt(x.kg*sc*x.solids/100,2);rows+=`<tr><td>${esc(x.name)}</td><td>${esc(tnpaFor(x.name))}</td><td>кг</td><td>${fmt(x.kg*sc,2)}</td><td>${x.solids==null?'':fmt(x.solids,2)}</td><td>${mass}</td></tr>`});
 rows+=`<tr><td>Вода</td><td>СТБ 1188, СанПиН 10-124</td><td>дм³</td><td>до ${fmt(syr,2)}</td><td></td><td></td></tr><tr><td>Выход сиропа</td><td></td><td>дм³</td><td>${fmt(syr,2)}</td><td></td><td></td></tr><tr class="band"><td colspan="6">Для приготовления напитка</td></tr><tr><td>Вода</td><td>СТБ 1188, СанПиН 10-124</td><td>дм³</td><td>до ${fmt(vol,0)}</td><td></td><td></td></tr>`;
 let co2=items.find(x=>x.name==="Диоксид углерода");if(co2)rows+=`<tr><td>Двуокись углерода</td><td>ГОСТ 8050</td><td>кг</td><td>${fmt(co2.kg*sc,2)}</td><td></td><td></td></tr>`;
 let known=items.reduce((a,x)=>a+(x.solids==null?0:x.kg*sc*x.solids/100),0),sugar=items.find(x=>x.key==="sugar"),sugarSV=sugar&&sugar.solids!=null?sugar.kg*sc*sugar.solids/100:0,growth=sugarSV*.0526;
 rows+=`<tr><td>Итого сухих веществ</td><td></td><td>кг</td><td></td><td></td><td>${fmt(known,2)}</td></tr><tr><td>Прирост сухих веществ за счёт<br>100-% инверсии сахарозы</td><td></td><td>кг</td><td></td><td></td><td>${fmt(growth,2)}</td></tr><tr><td>Всего сухих веществ в полностью<br>инвертированном напитке</td><td></td><td>кг</td><td></td><td></td><td>${fmt(known+growth,2)}</td></tr>`;
 return `<div class="sheet"><div class="page-no">С.71.</div><div class="code">РЦ BY 100534628.000 - 2016</div><div class="title">Напиток безалкогольный газированный Дюшес AN1374</div><div class="subtitle">Рецептура на ${fmt(syr,2)} дм³ сиропа или на ${fmt(vol,0)} дм³ готового напитка (без учета потерь).</div>
 <table class="recipe"><colgroup><col style="width:27%"><col style="width:27%"><col style="width:8%"><col style="width:13%"><col style="width:12%"><col style="width:13%"></colgroup><thead><tr><th rowspan="2">Наименование сырья</th><th rowspan="2">ТНПА на сырье</th><th colspan="2">Содержание сырья в<br>готовом сиропе</th><th colspan="2">Содержание сухих<br>веществ в сырье</th></tr><tr><th>Ед. изм.</th><th>Количество</th><th>Массовая<br>доля, %</th><th>Масса, кг</th></tr></thead><tbody>${rows}</tbody></table>
 <div class="notes"><b>Примечания:</b><ol><li>Свежеприготовленный напиток (из неинвертированного купажного сиропа) должен иметь массовую долю сухих веществ 9,3 ± 0,3 %</li><li>Свежеприготовленный купажный сироп (из неинвертированного сахарного сиропа) должен иметь долю сухих веществ 40,8 ± 1,0 %</li><li>При приготовлении напитка из сиропа объёмное соотношение сиропа и воды устанавливают 1 : 4.</li></ol></div>
 <div class="section-title">ХАРАКТЕРИСТИКИ НАПИТКА</div><table class="pairs"><tr><td>Тип:</td><td>газированный</td></tr><tr><td>Внешний вид:</td><td>прозрачный</td></tr><tr><td>Способ обработки:</td><td>непастеризованный с применением консерванта</td></tr><tr><td>Группа:</td><td>на ароматах</td></tr></table>
 <div class="section-title">ОРГАНОЛЕПТИЧЕСКИЕ ПОКАЗАТЕЛИ НАПИТКА</div><table class="pairs sensory"><tr><td>Внешний вид:</td><td>прозрачная жидкость без осадка и взвешенных частиц. Допускается лёгкая опалесценция, обусловленная особенностями используемого сырья.</td></tr><tr><td>Цвет:</td><td>от светло-жёлтого до соломенного</td></tr><tr><td>Вкус и аромат:</td><td>кисло-сладкий, свойственный дюшесу</td></tr></table>
 <div class="section-title">ФИЗИКО-ХИМИЧЕСКИЕ ПОКАЗАТЕЛИ НАПИТКА</div><table class="phys"><thead><tr><th>Наименование показателя</th><th>Норма</th></tr></thead><tbody><tr><td>Массовая доля сухих веществ, %</td><td>9,8 ± 0,3</td></tr><tr><td>Кислотность, см³ раствора гидроокиси натрия концентрацией 1,0 моль/дм³ на 100 см³</td><td>2,6 ± 0,3</td></tr><tr><td>Массовая доля двуокиси углерода, % не менее</td><td>0,4</td></tr><tr><td>Содержание бензоата натрия в пересчёте на бензойную кислоту, мг/1000 см³ готового напитка, не более</td><td>150</td></tr><tr><td>Стойкость, суток, не более:</td><td></td></tr><tr><td>Пищевая ценность:<br>• &nbsp; углеводы, г/100 см³<br>• &nbsp; энергетическая ценность, ккал/100 см³</td><td><br>9,5<br>36</td></tr></tbody></table>
 <div class="bottom-notes"><b>Примечание:</b><ol><li>Массовая доля сухих веществ в готовом напитке и сиропе определяется после проведения 100%-ной принудительной инверсии сахарозы по ГОСТ 6687.2.</li><li>Маркировка по СТБ 539 и СТБ 1100.</li></ol></div></div>`;
}
const printCss=`@page{size:A4 portrait;margin:8mm}*{box-sizing:border-box}html,body{margin:0;padding:0;background:#fff;color:#000;font-family:"Times New Roman",Times,serif}.sheet{width:194mm;margin:0 auto;font-size:8.15pt;line-height:1.06}.page-no{font-size:9pt;margin-bottom:4mm}.code{font-size:8.5pt;text-decoration:underline;font-style:italic;margin-bottom:4.5mm}.title{text-align:center;font-weight:700;font-size:11.2pt;margin-bottom:.5mm}.subtitle{text-align:center;font-style:italic;font-size:8.5pt;margin-bottom:1.5mm}.recipe,.phys{width:100%;border-collapse:collapse;table-layout:fixed}.recipe th,.recipe td,.phys th,.phys td{border:1px solid #000;padding:.7mm 1mm;text-align:center;vertical-align:middle}.recipe th,.phys th{font-weight:700}.recipe td:first-child,.recipe td:nth-child(2){line-height:1.03}.band td{font-weight:700;padding:.45mm}.notes{margin:1mm .8mm .5mm;font-size:7.8pt;font-style:italic}.notes>b,.bottom-notes>b{font-style:normal}.notes ol,.bottom-notes ol{margin:.3mm 0 0 4.5mm;padding-left:2.5mm}.notes li,.bottom-notes li{padding-left:1mm;margin:.25mm 0}.section-title{text-align:center;font-weight:700;font-size:9.3pt;margin:1.1mm 0 .35mm}.pairs{width:84%;margin:0 auto;border-collapse:collapse;font-size:8.2pt}.pairs td{padding:.25mm .8mm;vertical-align:top}.pairs td:first-child{width:28%;font-style:italic;text-decoration:underline}.sensory td{padding:.3mm .8mm}.phys{font-size:7.7pt;margin-top:.4mm}.phys th,.phys td{padding:.55mm 1mm}.phys th:last-child,.phys td:last-child{width:16%;text-align:center}.phys td:first-child{text-align:left}.bottom-notes{font-size:7.5pt;margin:.7mm .8mm 0}@media print{html,body{width:210mm;height:297mm}.sheet{break-inside:avoid;page-break-inside:avoid}}`;
function renderDocumentPreview(){let host=$("#paperPreview");if(!host)return;host.innerHTML=`<style>${printCss}</style>${documentBody()}`}
function printDocument(){const w=window.open("","_blank");if(!w){alert("Браузер заблокировал окно печати. Разрешите всплывающие окна для этого сайта и повторите.");return}w.document.open();w.document.write(`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Дюшес AN1374 — рецептура</title><style>${printCss}</style></head><body>${documentBody()}<script>window.onload=()=>setTimeout(()=>window.print(),180)<\/script></body></html>`);w.document.close()}
function persist(){localStorage.setItem("bs_items",JSON.stringify(items))}
["volume","ratio","loss"].forEach(id=>$("#"+id).oninput=render);
$("#reset").onclick=()=>{items=structuredClone(base);localStorage.removeItem("bs_items");$("#volume").value=1000;$("#ratio").value=4;$("#loss").value=0;render()};
$("#save").onclick=()=>{persist();localStorage.setItem("bs_lab",JSON.stringify({fresh:$("#labFresh").value,inv:$("#labInv").value,acid:$("#labAcid").value,note:$("#labNote").value}));alert("Версия сохранена на этом устройстве.")};
$("#add").onclick=()=>{let name=prompt("Название сырья:");if(name){items.push({name,cat:"Другое",kg:0,solids:null});persist();render()}};
$$(".tab").forEach(b=>b.onclick=()=>{$$(".tab").forEach(x=>x.classList.remove("active"));$$(".tabpane").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.tab).classList.add("active")});
$$(".nav").forEach(b=>b.onclick=()=>{$$(".nav").forEach(x=>x.classList.remove("active"));$$(".view").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.view).classList.add("active")});
$("#theme").onclick=()=>document.body.classList.toggle("dark");
let lab=JSON.parse(localStorage.getItem("bs_lab")||"{}");$("#labFresh").value=lab.fresh||"";$("#labInv").value=lab.inv||"";$("#labAcid").value=lab.acid||"";$("#labNote").value=lab.note||"";
$("#csv").onclick=()=>{let rows=[["Наименование","Количество, кг","СВ, %"],...items.map(x=>[x.name,(x.kg*scale()).toFixed(3),x.solids??""])];let csv="\ufeff"+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(";")).join("\n");let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download="beverage_studio_recipe.csv";a.click()};
$("#printDocument").onclick=printDocument;
render();
